import type { Metadata, Viewport } from "next";
import { IBM_Plex_Mono, Space_Grotesk } from "next/font/google";
import { site } from "@/content/site";
import { Nav } from "@/components/Nav";
import { Footer } from "@/components/Footer";
import "./globals.css";

// Retro-technical pairing: Space Grotesk for headings/body,
// IBM Plex Mono for labels, stats, and terminal accents.
const sans = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

const mono = IBM_Plex_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  display: "swap",
  weight: ["400", "500"],
});

// Base URL for absolute metadata (Open Graph / preview image) URLs.
// Defaults to the canonical domain in content/site.ts so preview cards point
// at aadityasharma.net rather than a deploy-specific vercel.app hostname.
// Set NEXT_PUBLIC_SITE_URL to override (e.g. for a preview deployment).
const metadataBase = new URL(process.env.NEXT_PUBLIC_SITE_URL ?? site.url);

const pageTitle = `${site.name} — ${site.tagline}`;

export const metadata: Metadata = {
  metadataBase,
  title: {
    default: pageTitle,
    template: `%s — ${site.name}`,
  },
  description: site.blurb,
  // The preview image itself is generated by app/opengraph-image.tsx and
  // wired in automatically; these fields fill out the rest of the card.
  openGraph: {
    type: "website",
    siteName: site.name,
    title: pageTitle,
    description: site.blurb,
  },
  twitter: {
    card: "summary_large_image",
    title: pageTitle,
    description: site.blurb,
  },
};

export const viewport: Viewport = {
  themeColor: "#09090b",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${sans.variable} ${mono.variable}`}>
      <body>
        <div id="top" />
        <Nav />
        <main className="pt-16">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
